name: Terraform Apply

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActions-Role
          aws-region: eu-west-2

      - name: Create terraform.tfvars
        working-directory: ./terraform
        run: |
          cat > terraform.tfvars <<EOF
          region = "eu-west-2"

          cloudflare_zone_id     = "8dbeaf5a7eca46cc066c0a03b0d1a402"
          domain_name            = "tm.fazops.com"
          record_name            = "tm"
          record_type            = "CNAME"
          evaluate_target_health = false

          cloudflare_api_token = ""

          acm_certificate_arn = "${{ secrets.ACM_CERT_ARN }}"
          container_image     = "${{ secrets.CONTAINER_IMAGE }}"
          app_bucket_name     = "${{ secrets.APP_BUCKET_NAME }}"
          EOF

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: terraform apply -auto-approve \
               -var="cloudflare_api_token=${CLOUDFLARE_API_TOKEN}" \
               -var-file=terraform.tfvars
