name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::598130604507:role/GitHubActions-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.6

      - name: Create auto.tfvars
        working-directory: terraform
        run: echo "${{ secrets.TF_VARS }}" | base64 --decode > auto.tfvars

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Destroy
        working-directory: terraform
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          terraform destroy \
            -var-file=auto.tfvars \
            -var="cloudflare_api_token=${CLOUDFLARE_API_TOKEN}" \
            -auto-approve \
            -input=false
