name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::598130604507:role/GitHubActions-Role
          aws-region: eu-west-2

      - name: Write terraform.tfvars
        working-directory: ./terraform
        run: |
          cat <<'EOF' > terraform.tfvars
              ${{ secrets.TF_VARS }}
                        EOF

      - name: Inject Cloudflare Token
        working-directory: ./terraform
        run: |
          sed -i 's|cloudflare_api_token = ""|cloudflare_api_token = "${{ secrets.CLOUDFLARE_API_TOKEN }}"|' terraform.tfvars

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve -var-file=terraform.tfvars
