name: Terraform Plan

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types: [completed]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2

jobs:
  terraform-plan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::598130604507:role/GitHubActions-Role
          aws-region: eu-west-2

      - name: Write terraform.tfvars from Secret
        working-directory: ./terraform
        run: |
          printf "%s" "${{ secrets.TF_VARS }}" > terraform.tfvars

      - name: Inject Cloudflare Token
        working-directory: ./terraform
        run: |
          sed -i "s|cloudflare_api_token = \"\"|cloudflare_api_token = \"${{ secrets.CLOUDFLARE_API_TOKEN }}\"|" terraform.tfvars

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -var-file=terraform.tfvars
